// Curated question bank for the learning module.
// Questions are seed content drawn from standard CS algorithms-and-data-structures
// curriculum. Add or replace questions freely — the runtime just reads this array.

import type { Question } from "./types";

export const QUESTION_BANK: Question[] = [

  // ── ALGORITHM ANALYSIS ─────────────────────────────────────────────────────
  {
    id: "algo-1", topic: "algorithms", kind: "multiple-choice",
    prompt: "What does Big-O notation describe?",
    choices: [
      "An algorithm's exact runtime in milliseconds",
      "An upper bound on growth rate as input size increases",
      "A lower bound on memory usage",
      "The best-case performance of an algorithm",
    ],
    correctIndex: 1,
    explanation: "Big-O is an asymptotic upper bound on growth rate, ignoring constants and lower-order terms.",
    difficulty: "easy",
  },
  {
    id: "algo-2", topic: "algorithms", kind: "multiple-choice",
    prompt: "Which of the following has the slowest asymptotic growth?",
    choices: ["O(n²)", "O(n log n)", "O(n)", "O(log n)"],
    correctIndex: 3,
    explanation: "log n grows slowest among these. Order: O(1) < O(log n) < O(n) < O(n log n) < O(n²) < O(2ⁿ).",
    difficulty: "easy",
  },
  {
    id: "algo-3", topic: "algorithms", kind: "true-false",
    prompt: "An algorithm with O(n²) time complexity will always be slower than one with O(n log n) for any input size.",
    correct: false,
    explanation: "Big-O describes asymptotic behavior. For small n, constant factors can make O(n²) faster. Big-O only applies as n → ∞.",
    difficulty: "medium",
  },
  {
    id: "algo-4", topic: "algorithms", kind: "fill-blank",
    prompt: "An algorithm that runs T(n) = 5n² + 100n + 1000 has Big-O complexity O(____).",
    accepted: ["n^2", "n²", "n*n", "n*n", "n2"],
    explanation: "Drop constants and lower-order terms: 5n² dominates, so O(n²).",
    difficulty: "easy",
  },
  {
    id: "algo-5", topic: "algorithms", kind: "multiple-choice",
    prompt: "What is the difference between Big-O and Big-Θ (theta)?",
    choices: [
      "They are identical",
      "Big-O is upper bound only; Big-Θ is both upper and lower bound",
      "Big-Θ is for worst case; Big-O is for average case",
      "Big-Θ measures space; Big-O measures time",
    ],
    correctIndex: 1,
    explanation: "Big-Θ means tightly bounded — the growth rate is exactly that order, not just at most.",
    difficulty: "medium",
  },
  {
    id: "algo-6", topic: "algorithms", kind: "multi-select",
    prompt: "Which of the following are O(log n)?",
    choices: [
      "Binary search on a sorted array",
      "Linear search on an unsorted array",
      "Finding height of a balanced BST",
      "Merge sort",
      "Inserting into a balanced BST",
    ],
    correctIndices: [0, 2, 4],
    explanation: "Linear search is O(n); merge sort is O(n log n). The others split the search space in half each step.",
    difficulty: "medium",
  },
  {
    id: "algo-7", topic: "algorithms", kind: "ordering",
    prompt: "Order these complexities from fastest to slowest growth:",
    items: ["O(n²)", "O(log n)", "O(2ⁿ)", "O(n)", "O(n log n)"],
    correctOrder: [1, 3, 4, 0, 2],
    explanation: "log n < n < n log n < n² < 2ⁿ for sufficiently large n.",
    difficulty: "medium",
  },
  {
    id: "algo-8", topic: "algorithms", kind: "numeric",
    prompt: "How many operations does a Θ(log₂ n) algorithm perform on n = 1024 items? (approximate)",
    correct: 10,
    tolerance: 1,
    explanation: "log₂(1024) = 10, since 2¹⁰ = 1024.",
    difficulty: "easy",
  },

  // ── RECURSION ──────────────────────────────────────────────────────────────
  {
    id: "rec-1", topic: "recursion", kind: "multiple-choice",
    prompt: "What is the most important component of any recursive function?",
    choices: ["The return value", "A loop", "A base case", "A global variable"],
    correctIndex: 2,
    explanation: "Without a base case, recursion never terminates and causes stack overflow.",
    difficulty: "easy",
  },
  {
    id: "rec-2", topic: "recursion", kind: "fill-blank",
    prompt: "The recurrence T(n) = 2T(n/2) + n solves to O(n ____ n) by the master theorem.",
    accepted: ["log"],
    explanation: "Case 2 of the master theorem: a=2, b=2, f(n)=n matches n^log_b(a) = n¹, giving O(n log n). This is mergesort.",
    difficulty: "medium",
  },
  {
    id: "rec-3", topic: "recursion", kind: "true-false",
    prompt: "Every recursive algorithm can be converted into an iterative one.",
    correct: true,
    explanation: "Yes — using an explicit stack, any recursion can be simulated iteratively. The compiler does this for tail-recursive calls automatically in some languages.",
    difficulty: "medium",
  },
  {
    id: "rec-4", topic: "recursion", kind: "multiple-choice",
    prompt: "What is tail recursion?",
    choices: [
      "Recursion where the recursive call is the last operation",
      "Recursion that uses an array (the 'tail') for storage",
      "Recursion with two recursive calls",
      "Recursion limited to a fixed depth",
    ],
    correctIndex: 0,
    explanation: "Tail recursion lets the compiler reuse the current stack frame (tail-call optimization) — saving O(n) stack space.",
    difficulty: "medium",
  },
  {
    id: "rec-5", topic: "recursion", kind: "numeric",
    prompt: "What does fib(6) return for the standard Fibonacci sequence (fib(0)=0, fib(1)=1)?",
    correct: 8,
    explanation: "0, 1, 1, 2, 3, 5, 8 — fib(6) = 8.",
    difficulty: "easy",
  },
  {
    id: "rec-6", topic: "recursion", kind: "multi-select",
    prompt: "Which problems have natural recursive solutions?",
    choices: [
      "Tree traversal",
      "Tower of Hanoi",
      "Computing the average of an array",
      "Merge sort",
      "Iterating through an array index",
    ],
    correctIndices: [0, 1, 3],
    explanation: "Recursion shines on self-similar problems. Computing an average and indexed iteration are naturally iterative.",
    difficulty: "medium",
  },

  // ── LINKED LISTS ───────────────────────────────────────────────────────────
  {
    id: "list-1", topic: "lists", kind: "multiple-choice",
    prompt: "What is the time complexity of inserting at the head of a singly linked list?",
    choices: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    correctIndex: 0,
    explanation: "Just create a new node and point it at the current head — constant time, no traversal needed.",
    difficulty: "easy",
  },
  {
    id: "list-2", topic: "lists", kind: "multiple-choice",
    prompt: "What is the time complexity of accessing the kth element of a singly linked list?",
    choices: ["O(1)", "O(log n)", "O(k)", "O(n²)"],
    correctIndex: 2,
    explanation: "Linked lists don't support random access — you must traverse k links from the head.",
    difficulty: "easy",
  },
  {
    id: "list-3", topic: "lists", kind: "true-false",
    prompt: "A doubly linked list uses more memory per node than a singly linked list.",
    correct: true,
    explanation: "Each node stores an extra pointer (back-link), roughly doubling pointer overhead per node.",
    difficulty: "easy",
  },
  {
    id: "list-4", topic: "lists", kind: "multiple-choice",
    prompt: "Given a pointer to a node (not the head) in a singly linked list, what is the cost to delete that node?",
    choices: ["O(1) by copying the next node's value", "O(n) — must traverse from head", "Impossible without the head", "O(log n)"],
    correctIndex: 0,
    explanation: "Trick: copy node.next.value into node, then delete node.next. Doesn't work if you're given the tail.",
    difficulty: "hard",
  },
  {
    id: "list-5", topic: "lists", kind: "fill-blank",
    prompt: "A linked list whose tail points back to the head is called a ____ linked list.",
    accepted: ["circular", "circularly"],
    explanation: "Circular linked lists let you traverse the list endlessly, useful for round-robin scheduling.",
    difficulty: "easy",
  },
  {
    id: "list-6", topic: "lists", kind: "multi-select",
    prompt: "Which operations are O(1) on a doubly linked list given a pointer to the node?",
    choices: [
      "Delete the node",
      "Insert before the node",
      "Find the kth element from head",
      "Insert after the node",
      "Get the previous node",
    ],
    correctIndices: [0, 1, 3, 4],
    explanation: "Random access (kth element) requires traversal — everything else is constant given the node pointer.",
    difficulty: "medium",
  },

  // ── STACKS & QUEUES ────────────────────────────────────────────────────────
  {
    id: "stack-1", topic: "stacks", kind: "multiple-choice",
    prompt: "Which access pattern describes a stack?",
    choices: ["FIFO (first in, first out)", "LIFO (last in, first out)", "Random access", "Priority order"],
    correctIndex: 1,
    explanation: "Stacks are LIFO — the last item pushed is the first popped. Think of a stack of plates.",
    difficulty: "easy",
  },
  {
    id: "stack-2", topic: "stacks", kind: "multiple-choice",
    prompt: "Which access pattern describes a queue?",
    choices: ["LIFO", "FIFO", "Random access", "Sorted order"],
    correctIndex: 1,
    explanation: "Queues are FIFO — first in, first out. Like a line at a checkout.",
    difficulty: "easy",
  },
  {
    id: "stack-3", topic: "stacks", kind: "fill-blank",
    prompt: "A double-ended queue that supports insertion/removal at both ends is called a ____.",
    accepted: ["deque", "dequeue"],
    explanation: "A deque (pronounced 'deck') generalizes both stacks and queues.",
    difficulty: "medium",
  },
  {
    id: "stack-4", topic: "stacks", kind: "true-false",
    prompt: "A stack can be implemented using only two queues.",
    correct: true,
    explanation: "Classic interview problem — push enqueues to q1; pop dequeues all but the last, moving them to q2, then returns the last.",
    difficulty: "hard",
  },
  {
    id: "stack-5", topic: "stacks", kind: "multi-select",
    prompt: "Which are common applications of stacks?",
    choices: [
      "Function call management (call stack)",
      "Breadth-first search",
      "Expression evaluation (postfix)",
      "Backtracking algorithms",
      "Print job scheduling",
    ],
    correctIndices: [0, 2, 3],
    explanation: "BFS uses a queue; print job scheduling is FIFO. The others are LIFO patterns.",
    difficulty: "medium",
  },
  {
    id: "stack-6", topic: "stacks", kind: "multiple-choice",
    prompt: "Evaluating the postfix expression `3 4 + 2 *` gives:",
    choices: ["10", "11", "14", "20"],
    correctIndex: 2,
    explanation: "(3+4) * 2 = 14. Postfix is evaluated using a stack: push operands, pop two on operator.",
    difficulty: "medium",
  },

  // ── TREES ─────────────────────────────────────────────────────────────────
  {
    id: "tree-1", topic: "trees", kind: "multiple-choice",
    prompt: "What is the maximum number of nodes in a binary tree of height h (root at height 0)?",
    choices: ["h", "2h", "2^h - 1", "2^(h+1) - 1"],
    correctIndex: 3,
    explanation: "A perfect binary tree has 1 + 2 + 4 + ... + 2^h = 2^(h+1) - 1 nodes.",
    difficulty: "medium",
  },
  {
    id: "tree-2", topic: "trees", kind: "ordering",
    prompt: "Given the tree: root=5 (left=3, right=8), 3 has left=1 and right=4. Order the nodes from in-order traversal:",
    items: ["1", "3", "4", "5", "8"],
    correctOrder: [0, 1, 2, 3, 4],
    explanation: "In-order = Left, Root, Right. Visiting yields 1, 3, 4, 5, 8 — sorted because this is also a BST.",
    difficulty: "medium",
  },
  {
    id: "tree-3", topic: "trees", kind: "fill-blank",
    prompt: "A traversal that visits Root, Left subtree, Right subtree is called ____ -order.",
    accepted: ["pre", "preorder"],
    explanation: "Pre-order: visit root before children. Post-order is the opposite.",
    difficulty: "easy",
  },
  {
    id: "tree-4", topic: "trees", kind: "true-false",
    prompt: "Every binary tree with n nodes has exactly n - 1 edges.",
    correct: true,
    explanation: "True for any tree (including non-binary): n nodes, n-1 edges, no cycles.",
    difficulty: "medium",
  },
  {
    id: "tree-5", topic: "trees", kind: "multiple-choice",
    prompt: "What traversal produces the nodes of a BST in sorted order?",
    choices: ["Pre-order", "In-order", "Post-order", "Level-order"],
    correctIndex: 1,
    explanation: "In-order traversal visits Left → Root → Right, which yields ascending order on a BST.",
    difficulty: "easy",
  },

  // ── BST ───────────────────────────────────────────────────────────────────
  {
    id: "bst-1", topic: "bst", kind: "multiple-choice",
    prompt: "What is the BST property?",
    choices: [
      "Each node has at most 2 children",
      "Left subtree values < node value < right subtree values",
      "All leaves are at the same depth",
      "Each node has a height balanced within 1",
    ],
    correctIndex: 1,
    explanation: "BST invariant: left descendants are all smaller, right descendants are all larger.",
    difficulty: "easy",
  },
  {
    id: "bst-2", topic: "bst", kind: "multiple-choice",
    prompt: "What is the worst-case height of a BST with n nodes?",
    choices: ["O(1)", "O(log n)", "O(√n)", "O(n)"],
    correctIndex: 3,
    explanation: "If you insert 1,2,3,...,n in order, the BST degenerates into a linked list of height n.",
    difficulty: "medium",
  },
  {
    id: "bst-3", topic: "bst", kind: "true-false",
    prompt: "Searching in a BST is always O(log n).",
    correct: false,
    explanation: "Only when balanced. A degenerate BST (sorted insertion) has search complexity O(n).",
    difficulty: "easy",
  },
  {
    id: "bst-4", topic: "bst", kind: "multiple-choice",
    prompt: "When deleting a node with two children from a BST, you replace it with:",
    choices: [
      "Its left child",
      "Its right child",
      "The maximum of the left subtree (in-order predecessor) or minimum of the right subtree (in-order successor)",
      "Any leaf in its subtree",
    ],
    correctIndex: 2,
    explanation: "To preserve the BST property, replace with the in-order predecessor or successor.",
    difficulty: "hard",
  },
  {
    id: "bst-5", topic: "bst", kind: "fill-blank",
    prompt: "The smallest element in a BST is the ____ -most node.",
    accepted: ["left", "leftmost"],
    explanation: "Repeatedly follow left pointers until you can't. Mirror: rightmost = max.",
    difficulty: "easy",
  },

  // ── BALANCED TREES ─────────────────────────────────────────────────────────
  {
    id: "bal-1", topic: "balance", kind: "multiple-choice",
    prompt: "What is the maximum allowed balance factor for any node in an AVL tree?",
    choices: ["0", "±1", "±2", "log n"],
    correctIndex: 1,
    explanation: "AVL trees require |height(left) - height(right)| ≤ 1 at every node.",
    difficulty: "medium",
  },
  {
    id: "bal-2", topic: "balance", kind: "multiple-choice",
    prompt: "After inserting a node that causes a left-heavy imbalance from a left child's left subtree, which rotation fixes it?",
    choices: ["Left rotation", "Right rotation", "Left-Right (double) rotation", "Right-Left (double) rotation"],
    correctIndex: 1,
    explanation: "Left-Left case → single right rotation. Mirror for right-right.",
    difficulty: "hard",
  },
  {
    id: "bal-3", topic: "balance", kind: "true-false",
    prompt: "Red-Black trees guarantee O(log n) operations but are not as strictly balanced as AVL trees.",
    correct: true,
    explanation: "RB trees allow longer paths (up to 2× the shortest) but rebalance with fewer rotations on average.",
    difficulty: "medium",
  },
  {
    id: "bal-4", topic: "balance", kind: "multi-select",
    prompt: "Which are properties of a Red-Black tree?",
    choices: [
      "Root is black",
      "Red nodes cannot have red children",
      "Every path from root to a null leaf has the same number of black nodes",
      "All leaves are at the same depth",
      "Height is at most 2 log₂(n+1)",
    ],
    correctIndices: [0, 1, 2, 4],
    explanation: "Equal-depth leaves is a property of perfect trees, not red-black trees.",
    difficulty: "hard",
  },

  // ── HEAPS ─────────────────────────────────────────────────────────────────
  {
    id: "heap-1", topic: "heaps", kind: "multiple-choice",
    prompt: "In a max-heap, where is the largest element?",
    choices: ["At the leftmost leaf", "At the rightmost leaf", "At the root", "At a random position"],
    correctIndex: 2,
    explanation: "By the heap property, the root is always the max in a max-heap (or min in a min-heap).",
    difficulty: "easy",
  },
  {
    id: "heap-2", topic: "heaps", kind: "multiple-choice",
    prompt: "What is the time complexity of building a heap from an unsorted array of n elements?",
    choices: ["O(n)", "O(n log n)", "O(log n)", "O(n²)"],
    correctIndex: 0,
    explanation: "Bottom-up heapify is O(n) — counterintuitive but provable. Inserting one-by-one would be O(n log n).",
    difficulty: "hard",
  },
  {
    id: "heap-3", topic: "heaps", kind: "fill-blank",
    prompt: "In an array-backed heap, the parent of index i is at index ____.",
    accepted: ["(i-1)/2", "(i - 1) / 2", "floor((i-1)/2)", "(i-1)>>1"],
    explanation: "Children of i are 2i+1 and 2i+2; parent is ⌊(i-1)/2⌋.",
    difficulty: "medium",
  },
  {
    id: "heap-4", topic: "heaps", kind: "true-false",
    prompt: "Heapsort runs in-place in O(n log n) time in the worst case.",
    correct: true,
    explanation: "Heapsort: build the heap in-place (O(n)), then extract n times (O(n log n) total). Worst case is O(n log n).",
    difficulty: "medium",
  },
  {
    id: "heap-5", topic: "heaps", kind: "multiple-choice",
    prompt: "What is the time complexity of finding the maximum in a min-heap of n elements?",
    choices: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 2,
    explanation: "The max could be any leaf in a min-heap — you have to scan all n/2 leaves.",
    difficulty: "hard",
  },

  // ── HASHING ───────────────────────────────────────────────────────────────
  {
    id: "hash-1", topic: "hashing", kind: "multiple-choice",
    prompt: "What does it mean when two keys hash to the same index?",
    choices: ["Hash table is full", "A collision occurred", "The keys are equal", "Performance becomes O(n²)"],
    correctIndex: 1,
    explanation: "A collision is when distinct keys map to the same slot — handled via chaining or open addressing.",
    difficulty: "easy",
  },
  {
    id: "hash-2", topic: "hashing", kind: "multiple-choice",
    prompt: "What is the load factor of a hash table?",
    choices: [
      "Number of items × cost per operation",
      "Items / table size",
      "Number of collisions",
      "log₂(table size)",
    ],
    correctIndex: 1,
    explanation: "Load factor α = n/m. Most implementations resize when α exceeds ~0.7.",
    difficulty: "easy",
  },
  {
    id: "hash-3", topic: "hashing", kind: "true-false",
    prompt: "Hash table operations are O(1) in the worst case.",
    correct: false,
    explanation: "Average case is O(1) with a good hash and bounded load factor. Worst case is O(n) when all items collide.",
    difficulty: "medium",
  },
  {
    id: "hash-4", topic: "hashing", kind: "multi-select",
    prompt: "Which are valid collision resolution strategies?",
    choices: [
      "Separate chaining (linked list per bucket)",
      "Linear probing",
      "Quadratic probing",
      "Double hashing",
      "Skip the colliding key",
    ],
    correctIndices: [0, 1, 2, 3],
    explanation: "Skipping a key would lose data. The other four are standard collision strategies.",
    difficulty: "medium",
  },
  {
    id: "hash-5", topic: "hashing", kind: "fill-blank",
    prompt: "A hash function that produces evenly distributed outputs is said to satisfy the ____ assumption.",
    accepted: ["uniform hashing", "uniform", "simple uniform hashing"],
    explanation: "Simple uniform hashing: each key is equally likely to hash to any slot.",
    difficulty: "hard",
  },

  // ── SETS & MAPS ───────────────────────────────────────────────────────────
  {
    id: "set-1", topic: "sets", kind: "multiple-choice",
    prompt: "What is the main difference between a set and a list?",
    choices: [
      "Sets are sorted; lists are not",
      "Sets contain no duplicates; lists allow duplicates",
      "Sets are immutable; lists are mutable",
      "Sets store key-value pairs; lists store values",
    ],
    correctIndex: 1,
    explanation: "Sets are unordered collections of unique elements. Lists allow duplicates and preserve order.",
    difficulty: "easy",
  },
  {
    id: "set-2", topic: "sets", kind: "multiple-choice",
    prompt: "Union-Find (disjoint set) with union by rank and path compression has nearly which time per operation?",
    choices: ["O(1)", "O(log n)", "O(α(n)) — inverse Ackermann", "O(n)"],
    correctIndex: 2,
    explanation: "α(n) grows incredibly slowly — practically O(1) for any realistic n.",
    difficulty: "hard",
  },
  {
    id: "set-3", topic: "sets", kind: "true-false",
    prompt: "A hash set typically has faster lookup than a tree set, but a tree set keeps elements ordered.",
    correct: true,
    explanation: "Hash sets are O(1) avg; tree sets (red-black tree backed) are O(log n) but support range queries and ordered iteration.",
    difficulty: "medium",
  },

  // ── SORTING ───────────────────────────────────────────────────────────────
  {
    id: "sort-1", topic: "sorting", kind: "multiple-choice",
    prompt: "Which sorting algorithm has worst-case O(n²) time but excellent average-case performance?",
    choices: ["Merge sort", "Heap sort", "Quick sort", "Counting sort"],
    correctIndex: 2,
    explanation: "Quicksort is O(n log n) avg but degenerates to O(n²) on already-sorted input with naive pivot choice.",
    difficulty: "easy",
  },
  {
    id: "sort-2", topic: "sorting", kind: "multi-select",
    prompt: "Which sorting algorithms are stable?",
    choices: [
      "Merge sort",
      "Quicksort (typical)",
      "Heap sort",
      "Insertion sort",
      "Selection sort (typical)",
    ],
    correctIndices: [0, 3],
    explanation: "A stable sort preserves relative order of equal keys. Quicksort, heap sort, and selection sort are typically unstable.",
    difficulty: "medium",
  },
  {
    id: "sort-3", topic: "sorting", kind: "fill-blank",
    prompt: "The lower bound for any comparison-based sort is Ω(n ____ n).",
    accepted: ["log"],
    explanation: "By an information-theoretic argument: n! arrangements require log₂(n!) ≈ n log n comparisons.",
    difficulty: "hard",
  },
  {
    id: "sort-4", topic: "sorting", kind: "true-false",
    prompt: "Counting sort is faster than quicksort for large n.",
    correct: false,
    explanation: "Counting sort is O(n+k) where k is the value range. It's only faster when k is small relative to n log n.",
    difficulty: "medium",
  },
  {
    id: "sort-5", topic: "sorting", kind: "multiple-choice",
    prompt: "What is the worst-case space complexity of merge sort?",
    choices: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 2,
    explanation: "Merge sort needs O(n) auxiliary space for the merge buffer.",
    difficulty: "easy",
  },
  {
    id: "sort-6", topic: "sorting", kind: "multiple-choice",
    prompt: "Insertion sort runs in O(n) time on which input?",
    choices: ["Random data", "Reversed data", "Already sorted data", "All-equal data"],
    correctIndex: 2,
    explanation: "Best case O(n): one pass with no shifts. Already-sorted is its sweet spot — adaptive sorts exploit this.",
    difficulty: "medium",
  },

  // ── MERGE SORT ────────────────────────────────────────────────────────────
  {
    id: "merge-1", topic: "merge", kind: "multiple-choice",
    prompt: "What is the recurrence for merge sort?",
    choices: ["T(n) = T(n/2) + n", "T(n) = 2T(n/2) + n", "T(n) = 2T(n-1) + 1", "T(n) = T(n-1) + n"],
    correctIndex: 1,
    explanation: "Two recursive calls on halves (2T(n/2)) plus linear merge (n) = T(n) = 2T(n/2) + n = O(n log n).",
    difficulty: "medium",
  },
  {
    id: "merge-2", topic: "merge", kind: "true-false",
    prompt: "Merge sort can be implemented iteratively using a bottom-up approach.",
    correct: true,
    explanation: "Bottom-up merge sort merges adjacent runs of doubling size: 1→2→4→…, no recursion needed.",
    difficulty: "medium",
  },
  {
    id: "merge-3", topic: "merge", kind: "ordering",
    prompt: "Order the steps of merge sort in execution order:",
    items: ["Merge sorted halves", "Recursively sort right half", "Recursively sort left half", "Divide array in two"],
    correctOrder: [3, 2, 1, 0],
    explanation: "Divide → conquer left → conquer right → combine.",
    difficulty: "easy",
  },

  // ── RADIX SORT ────────────────────────────────────────────────────────────
  {
    id: "radix-1", topic: "radix", kind: "multiple-choice",
    prompt: "Radix sort runs in O(?) time on n integers with at most k digits.",
    choices: ["O(n)", "O(nk)", "O(n log n)", "O(n²)"],
    correctIndex: 1,
    explanation: "k passes, each O(n+b) where b is the base — typically simplified to O(nk).",
    difficulty: "medium",
  },
  {
    id: "radix-2", topic: "radix", kind: "true-false",
    prompt: "Radix sort uses comparisons between full keys.",
    correct: false,
    explanation: "Radix sort is non-comparison: it sorts digit by digit using a stable bucket sort.",
    difficulty: "easy",
  },
  {
    id: "radix-3", topic: "radix", kind: "fill-blank",
    prompt: "____ -significant-digit (LSD) radix sort processes digits from right to left.",
    accepted: ["Least", "least"],
    explanation: "LSD = Least Significant Digit; MSD goes the other way.",
    difficulty: "easy",
  },

  // ── GRAPHS ────────────────────────────────────────────────────────────────
  {
    id: "graph-1", topic: "graphs", kind: "multiple-choice",
    prompt: "Which traversal uses a queue?",
    choices: ["DFS", "BFS", "Both use stacks", "Neither"],
    correctIndex: 1,
    explanation: "BFS uses a FIFO queue to visit nearest neighbors first. DFS uses a stack (or recursion).",
    difficulty: "easy",
  },
  {
    id: "graph-2", topic: "graphs", kind: "multiple-choice",
    prompt: "What is the space complexity of an adjacency matrix for a graph with V vertices?",
    choices: ["O(V)", "O(V + E)", "O(V²)", "O(E)"],
    correctIndex: 2,
    explanation: "An adjacency matrix is V×V, regardless of how sparse the graph is.",
    difficulty: "easy",
  },
  {
    id: "graph-3", topic: "graphs", kind: "true-false",
    prompt: "An adjacency list is more space-efficient than an adjacency matrix for sparse graphs.",
    correct: true,
    explanation: "Adjacency list is O(V+E); matrix is O(V²). When E ≪ V², the list wins big.",
    difficulty: "medium",
  },
  {
    id: "graph-4", topic: "graphs", kind: "multi-select",
    prompt: "Which problems can BFS solve efficiently?",
    choices: [
      "Shortest path in an unweighted graph",
      "Detecting cycles",
      "Topological sort",
      "Connected components",
      "Single-source shortest paths in a weighted graph",
    ],
    correctIndices: [0, 1, 3],
    explanation: "Topological sort needs DFS; weighted shortest paths need Dijkstra. BFS handles unweighted distance and connectivity.",
    difficulty: "hard",
  },
  {
    id: "graph-5", topic: "graphs", kind: "fill-blank",
    prompt: "A graph traversal that visits all reachable vertices is called a ____ -first search when it goes deep before wide.",
    accepted: ["depth"],
    explanation: "DFS goes as deep as possible before backtracking; BFS visits all neighbors first.",
    difficulty: "easy",
  },

  // ── SHORTEST PATHS ─────────────────────────────────────────────────────────
  {
    id: "sp-1", topic: "shortest", kind: "multiple-choice",
    prompt: "Which algorithm finds shortest paths from one source on a graph with non-negative edge weights?",
    choices: ["Bellman-Ford", "Dijkstra", "Kruskal", "Floyd-Warshall"],
    correctIndex: 1,
    explanation: "Dijkstra requires non-negative weights. Bellman-Ford handles negatives but is slower.",
    difficulty: "easy",
  },
  {
    id: "sp-2", topic: "shortest", kind: "multiple-choice",
    prompt: "Which algorithm computes shortest paths between all pairs of vertices?",
    choices: ["Dijkstra", "Bellman-Ford", "Floyd-Warshall", "Kruskal"],
    correctIndex: 2,
    explanation: "Floyd-Warshall is O(V³) all-pairs. You can also run Dijkstra V times for sparse graphs.",
    difficulty: "medium",
  },
  {
    id: "sp-3", topic: "shortest", kind: "true-false",
    prompt: "Dijkstra's algorithm works correctly on graphs with negative edge weights.",
    correct: false,
    explanation: "Dijkstra's greedy choice is invalidated by negative weights. Use Bellman-Ford instead.",
    difficulty: "medium",
  },
  {
    id: "sp-4", topic: "shortest", kind: "multiple-choice",
    prompt: "What data structure makes Dijkstra's algorithm O((V+E) log V)?",
    choices: ["Stack", "Queue", "Binary min-heap (priority queue)", "Hash table"],
    correctIndex: 2,
    explanation: "A min-heap-backed priority queue gives O(log V) extract-min. Fibonacci heaps drop it to O(E + V log V).",
    difficulty: "hard",
  },

  // ── SPANNING TREES ─────────────────────────────────────────────────────────
  {
    id: "span-1", topic: "span", kind: "multiple-choice",
    prompt: "What is a minimum spanning tree (MST)?",
    choices: [
      "A tree with the minimum number of nodes",
      "A subgraph that connects all vertices with minimum total edge weight and no cycles",
      "The shortest path tree from a single source",
      "A balanced binary tree of graph vertices",
    ],
    correctIndex: 1,
    explanation: "MST: connect all V vertices with V-1 edges, minimizing total weight, no cycles.",
    difficulty: "easy",
  },
  {
    id: "span-2", topic: "span", kind: "multi-select",
    prompt: "Which algorithms find a Minimum Spanning Tree?",
    choices: ["Kruskal's", "Prim's", "Dijkstra's", "Borůvka's", "Bellman-Ford"],
    correctIndices: [0, 1, 3],
    explanation: "Dijkstra and Bellman-Ford are shortest-path algorithms, not MST.",
    difficulty: "medium",
  },
  {
    id: "span-3", topic: "span", kind: "true-false",
    prompt: "Kruskal's algorithm uses a Union-Find (disjoint set) data structure.",
    correct: true,
    explanation: "Kruskal's adds edges in weight order, using Union-Find to detect when adding an edge would create a cycle.",
    difficulty: "medium",
  },
  {
    id: "span-4", topic: "span", kind: "multiple-choice",
    prompt: "How many edges does a MST of n vertices have?",
    choices: ["n", "n - 1", "n + 1", "2n"],
    correctIndex: 1,
    explanation: "Any tree on n nodes has exactly n-1 edges.",
    difficulty: "easy",
  },

  // ── ADDITIONAL: ALGORITHM ANALYSIS ─────────────────────────────────────────
  {
    id: "algo-9", topic: "algorithms", kind: "multiple-choice",
    prompt: "Which of these is asymptotically equal to O(n log n)?",
    choices: ["O(n log n²)", "O(log(n!))", "O(n²/log n)", "O(2^log n)"],
    correctIndex: 1,
    explanation: "log(n!) = Θ(n log n) by Stirling's approximation: log(n!) ≈ n log n - n.",
    difficulty: "hard",
  },
  {
    id: "algo-10", topic: "algorithms", kind: "matching",
    prompt: "Match each algorithm to its average-case time complexity:",
    pairs: [
      { left: "Linear search", right: "O(n)" },
      { left: "Binary search", right: "O(log n)" },
      { left: "Merge sort",    right: "O(n log n)" },
      { left: "Bubble sort",   right: "O(n²)" },
    ],
    explanation: "These four are foundational baselines — memorize them.",
    difficulty: "easy",
  },
  {
    id: "algo-11", topic: "algorithms", kind: "true-false",
    prompt: "Amortized analysis gives an upper bound on the average cost per operation in a worst-case sequence.",
    correct: true,
    explanation: "Amortized cost averages out expensive operations (e.g., array doubling) across many cheap ones.",
    difficulty: "hard",
  },
  {
    id: "algo-12", topic: "algorithms", kind: "multiple-choice",
    prompt: "Doubling an array's capacity when full gives what amortized cost per insertion?",
    choices: ["O(1)", "O(log n)", "O(√n)", "O(n)"],
    correctIndex: 0,
    explanation: "Total work to insert n items is O(n) (geometric series); amortized per insert is O(1).",
    difficulty: "hard",
  },
  {
    id: "algo-13", topic: "algorithms", kind: "fill-blank",
    prompt: "If f(n) = O(g(n)) and g(n) = O(h(n)), then f(n) = O(____).",
    accepted: ["h(n)", "h"],
    explanation: "Big-O is transitive — bounds compose.",
    difficulty: "medium",
  },
  {
    id: "algo-14", topic: "algorithms", kind: "numeric",
    prompt: "An O(n²) algorithm processes n=100 in 1 second. About how many seconds for n=1000?",
    correct: 100,
    tolerance: 5,
    explanation: "n grows 10×, n² grows 100×, so ~100 seconds.",
    difficulty: "medium",
  },
  {
    id: "algo-15", topic: "algorithms", kind: "multiple-choice",
    prompt: "Which is true about Big-Ω (omega)?",
    choices: [
      "Upper bound on growth",
      "Lower bound on growth",
      "Tight bound on growth",
      "Average case only",
    ],
    correctIndex: 1,
    explanation: "Big-Ω is a lower bound. Big-O is upper, Big-Θ is tight.",
    difficulty: "easy",
  },

  // ── ADDITIONAL: RECURSION ──────────────────────────────────────────────────
  {
    id: "rec-7", topic: "recursion", kind: "multiple-choice",
    prompt: "What does the recurrence T(n) = T(n-1) + 1 solve to?",
    choices: ["O(log n)", "O(n)", "O(n log n)", "O(n²)"],
    correctIndex: 1,
    explanation: "Each level adds 1 work; n levels → O(n). Like a single-recursion linear traversal.",
    difficulty: "medium",
  },
  {
    id: "rec-8", topic: "recursion", kind: "multiple-choice",
    prompt: "Naive recursive Fibonacci has time complexity:",
    choices: ["O(n)", "O(n log n)", "O(n²)", "O(2ⁿ)"],
    correctIndex: 3,
    explanation: "T(n) = T(n-1) + T(n-2) + 1 grows like the golden ratio φⁿ ≈ 1.618ⁿ — exponential.",
    difficulty: "medium",
  },
  {
    id: "rec-9", topic: "recursion", kind: "true-false",
    prompt: "Memoization can reduce naive recursive Fibonacci from O(2ⁿ) to O(n).",
    correct: true,
    explanation: "Each fib(k) is computed once and cached; n unique subproblems → O(n) time, O(n) space.",
    difficulty: "easy",
  },
  {
    id: "rec-10", topic: "recursion", kind: "ordering",
    prompt: "Order the steps to design a recursive algorithm:",
    items: [
      "Make recursive calls on smaller subproblems",
      "Identify the base case",
      "Combine results from subproblems",
      "Decide how to break the problem into smaller subproblems",
    ],
    correctOrder: [1, 3, 0, 2],
    explanation: "Base case → divide → recurse → combine. The classic recursive design pattern.",
    difficulty: "medium",
  },
  {
    id: "rec-11", topic: "recursion", kind: "fill-blank",
    prompt: "A recursive function calling itself ___ times before reaching the base case has stack depth O(times).",
    accepted: ["n", "k"],
    explanation: "Each call adds a stack frame; depth = number of recursions before hitting base.",
    difficulty: "easy",
  },

  // ── ADDITIONAL: LISTS ──────────────────────────────────────────────────────
  {
    id: "list-7", topic: "lists", kind: "multiple-choice",
    prompt: "Reversing a singly linked list of n nodes takes:",
    choices: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    correctIndex: 2,
    explanation: "Walk the list once, flipping pointers as you go — linear time, constant extra space.",
    difficulty: "medium",
  },
  {
    id: "list-8", topic: "lists", kind: "true-false",
    prompt: "Floyd's tortoise-and-hare algorithm detects a cycle in a linked list using O(1) extra space.",
    correct: true,
    explanation: "Two pointers (slow=1 step, fast=2 steps). If they meet, there's a cycle. O(n) time, O(1) space.",
    difficulty: "hard",
  },
  {
    id: "list-9", topic: "lists", kind: "multi-select",
    prompt: "Compared to arrays, linked lists are better when:",
    choices: [
      "You need fast random access by index",
      "You frequently insert/delete at the front",
      "Memory layout / cache locality matters most",
      "Size changes dynamically and is unpredictable",
      "You need O(1) length queries",
    ],
    correctIndices: [1, 3],
    explanation: "Arrays win on cache locality, random access, and length. Lists win on cheap insert/delete and dynamic size.",
    difficulty: "medium",
  },
  {
    id: "list-10", topic: "lists", kind: "multiple-choice",
    prompt: "What is the time complexity of finding the middle of a linked list using two pointers?",
    choices: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
    correctIndex: 2,
    explanation: "Tortoise-and-hare: fast pointer moves 2× per step. When fast hits the end, slow is at the middle. O(n).",
    difficulty: "medium",
  },

  // ── ADDITIONAL: STACKS & QUEUES ────────────────────────────────────────────
  {
    id: "stack-7", topic: "stacks", kind: "multiple-choice",
    prompt: "Which problem is naturally solved with a stack?",
    choices: [
      "Shortest path in a graph",
      "Matching parentheses in an expression",
      "Round-robin scheduling",
      "Finding the kth smallest element",
    ],
    correctIndex: 1,
    explanation: "Push '(' on open, pop on close, mismatch → invalid. Quintessential stack problem.",
    difficulty: "easy",
  },
  {
    id: "stack-8", topic: "stacks", kind: "true-false",
    prompt: "A queue can be implemented using two stacks with amortized O(1) per enqueue/dequeue.",
    correct: true,
    explanation: "Enqueue pushes to s1. Dequeue: if s2 empty, pour s1 into s2 (reversing), then pop s2. Amortized O(1).",
    difficulty: "hard",
  },
  {
    id: "stack-9", topic: "stacks", kind: "fill-blank",
    prompt: "A bounded queue implemented in a fixed-size array with wrap-around indices is called a ____ queue.",
    accepted: ["circular", "ring"],
    explanation: "Circular (ring) buffer: head/tail indices wrap modulo capacity. Used in OS schedulers, audio buffers.",
    difficulty: "medium",
  },
  {
    id: "stack-10", topic: "stacks", kind: "multiple-choice",
    prompt: "Converting infix to postfix notation typically uses:",
    choices: ["A queue", "A stack (Shunting-yard)", "A heap", "Recursion only"],
    correctIndex: 1,
    explanation: "Dijkstra's shunting-yard algorithm uses an operator stack to manage precedence.",
    difficulty: "medium",
  },
  {
    id: "stack-11", topic: "stacks", kind: "ordering",
    prompt: "Stack starts empty. Apply: push(1), push(2), push(3), pop, push(4), pop. What's left from bottom to top?",
    items: ["1", "2"],
    correctOrder: [0, 1],
    explanation: "After push(1,2,3): [1,2,3]. pop→[1,2]. push(4)→[1,2,4]. pop→[1,2].",
    difficulty: "easy",
  },

  // ── ADDITIONAL: TREES ──────────────────────────────────────────────────────
  {
    id: "tree-6", topic: "trees", kind: "multiple-choice",
    prompt: "How many leaves does a complete binary tree of n nodes have (n odd)?",
    choices: ["⌈n/2⌉", "n/2", "log n", "n - 1"],
    correctIndex: 0,
    explanation: "In a complete binary tree, half (rounded up) of the nodes are leaves.",
    difficulty: "hard",
  },
  {
    id: "tree-7", topic: "trees", kind: "fill-blank",
    prompt: "A tree where every internal node has exactly two children and all leaves are at the same depth is called a ____ binary tree.",
    accepted: ["perfect", "full and complete"],
    explanation: "Perfect binary tree: complete + full + leaves at same depth. Has 2^(h+1) - 1 nodes.",
    difficulty: "medium",
  },
  {
    id: "tree-8", topic: "trees", kind: "multiple-choice",
    prompt: "Level-order traversal (BFS) of a tree uses which data structure?",
    choices: ["Stack", "Queue", "Heap", "Hash map"],
    correctIndex: 1,
    explanation: "BFS visits depth-by-depth using a FIFO queue. DFS uses a stack.",
    difficulty: "easy",
  },
  {
    id: "tree-9", topic: "trees", kind: "multi-select",
    prompt: "Which tree traversals visit the root last?",
    choices: ["Pre-order", "In-order", "Post-order", "Level-order", "Reverse pre-order"],
    correctIndices: [2],
    explanation: "Post-order: Left → Right → Root. Used for deleting/freeing trees and evaluating expression trees.",
    difficulty: "medium",
  },
  {
    id: "tree-10", topic: "trees", kind: "true-false",
    prompt: "The minimum height of a binary tree with n nodes is ⌊log₂ n⌋.",
    correct: true,
    explanation: "Achieved by a complete (or perfect) binary tree. Maximum height is n-1 (a straight chain).",
    difficulty: "medium",
  },

  // ── ADDITIONAL: BST ────────────────────────────────────────────────────────
  {
    id: "bst-6", topic: "bst", kind: "multiple-choice",
    prompt: "Inserting n random keys into a BST yields an expected height of:",
    choices: ["O(log n)", "O(√n)", "O(n)", "O(n log n)"],
    correctIndex: 0,
    explanation: "On random insertion, expected height is Θ(log n). But adversarial (sorted) insertion gives O(n).",
    difficulty: "hard",
  },
  {
    id: "bst-7", topic: "bst", kind: "true-false",
    prompt: "The in-order successor of a BST node always has no left child.",
    correct: true,
    explanation: "If a node has a right subtree, the successor is the leftmost node of that subtree — by definition has no left child.",
    difficulty: "hard",
  },
  {
    id: "bst-8", topic: "bst", kind: "ordering",
    prompt: "Insert 5, 3, 8, 1, 4 into an empty BST. The pre-order traversal yields:",
    items: ["1", "3", "4", "5", "8"],
    correctOrder: [3, 1, 0, 2, 4],
    explanation: "Pre-order = Root, Left, Right. Tree: root=5, 5.left=3 (3.left=1, 3.right=4), 5.right=8. Pre-order: 5,3,1,4,8.",
    difficulty: "hard",
  },
  {
    id: "bst-9", topic: "bst", kind: "multiple-choice",
    prompt: "Searching for a key in a BST has the same complexity as:",
    choices: [
      "Inserting that key",
      "Deleting that key",
      "Computing the tree's height",
      "All of the above",
    ],
    correctIndex: 3,
    explanation: "All three traverse a single root-to-leaf path: O(h) where h is the tree's height.",
    difficulty: "medium",
  },

  // ── ADDITIONAL: BALANCED TREES ─────────────────────────────────────────────
  {
    id: "bal-5", topic: "balance", kind: "multiple-choice",
    prompt: "An AVL tree of height h has at minimum how many nodes (Fibonacci-related)?",
    choices: ["h", "2h", "F(h+2) - 1", "2^h"],
    correctIndex: 2,
    explanation: "Fibonacci trees minimize node count for height. N(h) = N(h-1) + N(h-2) + 1.",
    difficulty: "hard",
  },
  {
    id: "bal-6", topic: "balance", kind: "true-false",
    prompt: "Insertion into an AVL tree may require at most one rotation (single or double) to rebalance.",
    correct: true,
    explanation: "After insertion, only the deepest unbalanced ancestor needs at most a double rotation. Deletion may need O(log n) rotations.",
    difficulty: "hard",
  },
  {
    id: "bal-7", topic: "balance", kind: "fill-blank",
    prompt: "In an AVL tree, the balance factor of a node is the height of its left subtree minus the height of its ____ subtree.",
    accepted: ["right"],
    explanation: "Balance factor = height(left) - height(right). Allowed values are -1, 0, +1.",
    difficulty: "easy",
  },
  {
    id: "bal-8", topic: "balance", kind: "multiple-choice",
    prompt: "Which property is unique to red-black trees vs AVL?",
    choices: [
      "Self-balancing",
      "O(log n) operations",
      "Color attribute on each node",
      "Stores ordered keys",
    ],
    correctIndex: 2,
    explanation: "Red-black trees encode balance via node colors. AVL uses height/balance factors.",
    difficulty: "medium",
  },

  // ── ADDITIONAL: HEAPS ──────────────────────────────────────────────────────
  {
    id: "heap-6", topic: "heaps", kind: "multiple-choice",
    prompt: "What is the time complexity of decrease-key in a binary min-heap?",
    choices: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 1,
    explanation: "After decreasing, sift up to restore heap property — at most log n swaps to root.",
    difficulty: "medium",
  },
  {
    id: "heap-7", topic: "heaps", kind: "fill-blank",
    prompt: "In a 0-indexed heap array, the left child of index i is at index ____.",
    accepted: ["2i+1", "2i + 1", "2*i+1"],
    explanation: "Children: 2i+1 (left) and 2i+2 (right). Parent: ⌊(i-1)/2⌋.",
    difficulty: "easy",
  },
  {
    id: "heap-8", topic: "heaps", kind: "true-false",
    prompt: "A heap is a complete binary tree, but not necessarily a binary search tree.",
    correct: true,
    explanation: "Heap property is a partial order (parent ≥/≤ children), not a total order between siblings. Left/right siblings are unordered.",
    difficulty: "medium",
  },
  {
    id: "heap-9", topic: "heaps", kind: "multi-select",
    prompt: "Which operations are O(log n) in a binary heap?",
    choices: [
      "Insert",
      "Extract min/max",
      "Find min/max",
      "Decrease/increase key",
      "Build heap from array",
    ],
    correctIndices: [0, 1, 3],
    explanation: "Find min/max is O(1) (root). Build-heap is O(n) bottom-up.",
    difficulty: "medium",
  },
  {
    id: "heap-10", topic: "heaps", kind: "ordering",
    prompt: "Order the steps to extract min from a min-heap:",
    items: [
      "Sift the new root down",
      "Save the root's value",
      "Move the last element to the root",
      "Decrement heap size",
    ],
    correctOrder: [1, 2, 3, 0],
    explanation: "Save root → move last to root → shrink size → sift down to restore heap property.",
    difficulty: "hard",
  },

  // ── ADDITIONAL: HASHING ────────────────────────────────────────────────────
  {
    id: "hash-6", topic: "hashing", kind: "multiple-choice",
    prompt: "When using linear probing, finding an empty slot for an insertion can cluster keys together. This is called:",
    choices: ["Cascading", "Primary clustering", "Hash collisions", "Load saturation"],
    correctIndex: 1,
    explanation: "Primary clustering: long contiguous runs of occupied slots. Quadratic probing helps mitigate this.",
    difficulty: "hard",
  },
  {
    id: "hash-7", topic: "hashing", kind: "true-false",
    prompt: "A perfect hash function maps each key to a unique slot with no collisions.",
    correct: true,
    explanation: "Perfect hashes exist when keys are known in advance. Achievable with two-level hashing on static sets.",
    difficulty: "medium",
  },
  {
    id: "hash-8", topic: "hashing", kind: "multiple-choice",
    prompt: "What happens to expected lookup time if load factor α is held constant as n grows?",
    choices: ["Stays O(1)", "Grows like O(log n)", "Grows like O(α)", "Grows like O(n)"],
    correctIndex: 0,
    explanation: "With chaining + simple uniform hashing, expected probe is 1+α/2, independent of n.",
    difficulty: "hard",
  },
  {
    id: "hash-9", topic: "hashing", kind: "matching",
    prompt: "Match the collision strategy to its key property:",
    pairs: [
      { left: "Separate chaining",     right: "Each slot holds a list of items" },
      { left: "Linear probing",        right: "Probe slot+1, slot+2, ..." },
      { left: "Quadratic probing",     right: "Probe slot+1², slot+2², ..." },
      { left: "Double hashing",        right: "Probe slot + i·h₂(key)" },
    ],
    explanation: "Each strategy trades off cache locality, clustering, and implementation complexity.",
    difficulty: "medium",
  },
  {
    id: "hash-10", topic: "hashing", kind: "fill-blank",
    prompt: "A hash function that maps similar inputs to similar outputs (used in similarity search) is called a ____-sensitive hash.",
    accepted: ["locality"],
    explanation: "LSH = Locality-Sensitive Hashing. Used in approximate nearest-neighbor search and deduplication.",
    difficulty: "hard",
  },

  // ── ADDITIONAL: SETS ───────────────────────────────────────────────────────
  {
    id: "set-4", topic: "sets", kind: "multiple-choice",
    prompt: "What does Union-Find use to ensure efficient `union` operations?",
    choices: ["Sorted order", "Union by rank or size", "Hash chaining", "Lazy deletion"],
    correctIndex: 1,
    explanation: "Union by rank/size attaches the shorter tree under the taller one, keeping trees shallow.",
    difficulty: "medium",
  },
  {
    id: "set-5", topic: "sets", kind: "true-false",
    prompt: "Path compression in Union-Find flattens the tree during `find` operations.",
    correct: true,
    explanation: "Each node visited during find is re-pointed to the root. Future finds run nearly in O(1).",
    difficulty: "medium",
  },
  {
    id: "set-6", topic: "sets", kind: "multi-select",
    prompt: "Which operations does the Set ADT typically provide?",
    choices: [
      "Add",
      "Contains",
      "Remove",
      "Index access (set[k])",
      "Union, intersection, difference",
    ],
    correctIndices: [0, 1, 2, 4],
    explanation: "Sets are unordered — no index access. Add, contains, remove, and bulk operations are standard.",
    difficulty: "easy",
  },
  {
    id: "set-7", topic: "sets", kind: "fill-blank",
    prompt: "Two sets are ____ if their intersection is empty.",
    accepted: ["disjoint"],
    explanation: "Disjoint sets share no elements. Union-Find is also called the disjoint-set data structure.",
    difficulty: "easy",
  },

  // ── ADDITIONAL: SORTING ────────────────────────────────────────────────────
  {
    id: "sort-7", topic: "sorting", kind: "multiple-choice",
    prompt: "What is selection sort's main practical advantage?",
    choices: [
      "Best-case O(n) on sorted input",
      "Stable sort",
      "Minimum number of swaps (Θ(n))",
      "In-place with O(log n) extra space",
    ],
    correctIndex: 2,
    explanation: "Selection sort makes exactly n-1 swaps, useful when writes are expensive (e.g., flash memory).",
    difficulty: "medium",
  },
  {
    id: "sort-8", topic: "sorting", kind: "matching",
    prompt: "Match each sort to its worst-case time:",
    pairs: [
      { left: "Quicksort (naive pivot)", right: "O(n²)" },
      { left: "Merge sort",              right: "O(n log n)" },
      { left: "Heap sort",               right: "O(n log n)" },
      { left: "Insertion sort",          right: "O(n²)" },
    ],
    explanation: "Quicksort and insertion sort have O(n²) worst case. Merge and heap sort are guaranteed O(n log n).",
    difficulty: "medium",
  },
  {
    id: "sort-9", topic: "sorting", kind: "true-false",
    prompt: "Quicksort's worst case happens when the pivot is always the minimum or maximum.",
    correct: true,
    explanation: "Each partition produces an empty side and an n-1 side, leading to T(n) = T(n-1) + n = O(n²).",
    difficulty: "medium",
  },
  {
    id: "sort-10", topic: "sorting", kind: "multiple-choice",
    prompt: "Why does TimSort excel on real-world data?",
    choices: [
      "It detects already-sorted runs and merges them efficiently",
      "It uses GPU acceleration",
      "It always allocates O(1) memory",
      "It uses radix-style buckets",
    ],
    correctIndex: 0,
    explanation: "TimSort = adaptive merge sort. Real-world data has natural runs; TimSort exploits them for O(n) on sorted input.",
    difficulty: "medium",
  },
  {
    id: "sort-11", topic: "sorting", kind: "multi-select",
    prompt: "Which sorts are in-place (O(1) or O(log n) extra space)?",
    choices: [
      "Heap sort",
      "Merge sort",
      "Quicksort",
      "Insertion sort",
      "Counting sort",
    ],
    correctIndices: [0, 2, 3],
    explanation: "Merge sort needs O(n) buffer. Counting sort needs O(k) for counts. The others use O(log n) stack or O(1).",
    difficulty: "medium",
  },
  {
    id: "sort-12", topic: "sorting", kind: "fill-blank",
    prompt: "An ____ sort runs in O(n) time when input is already sorted (like insertion sort and TimSort).",
    accepted: ["adaptive"],
    explanation: "Adaptive sorts exploit existing order in the input. Non-adaptive sorts (selection, heap) take the same time regardless.",
    difficulty: "medium",
  },
  {
    id: "sort-13", topic: "sorting", kind: "numeric",
    prompt: "How many comparisons does the lower-bound theorem say are required to sort 8 distinct items?",
    correct: 16,
    tolerance: 2,
    explanation: "log₂(8!) = log₂(40320) ≈ 15.3, so at least 16 comparisons in the worst case.",
    difficulty: "hard",
  },

  // ── ADDITIONAL: MERGE SORT ─────────────────────────────────────────────────
  {
    id: "merge-4", topic: "merge", kind: "multiple-choice",
    prompt: "The merge step of mergesort is implemented in:",
    choices: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    correctIndex: 2,
    explanation: "Each element of the two sorted halves is examined once during the merge — linear in their combined size.",
    difficulty: "easy",
  },
  {
    id: "merge-5", topic: "merge", kind: "true-false",
    prompt: "Merge sort is naturally suitable for sorting linked lists in-place (O(1) extra space).",
    correct: true,
    explanation: "Linked-list merge doesn't need an auxiliary array — just rewire pointers. Unlike array mergesort which needs O(n) buffer.",
    difficulty: "hard",
  },
  {
    id: "merge-6", topic: "merge", kind: "multiple-choice",
    prompt: "External sorting (sorting data too large to fit in memory) typically uses a variant of:",
    choices: ["Quicksort", "Merge sort (k-way merge)", "Heap sort", "Counting sort"],
    correctIndex: 1,
    explanation: "k-way external merge sort: sort chunks that fit in memory, then merge them via a heap. Standard for DB sort and disk-based pipelines.",
    difficulty: "hard",
  },

  // ── ADDITIONAL: RADIX SORT ─────────────────────────────────────────────────
  {
    id: "radix-4", topic: "radix", kind: "multiple-choice",
    prompt: "Radix sort's stability is critical because:",
    choices: [
      "Each pass must preserve the order from previous digit passes",
      "It runs in parallel",
      "Inputs may contain duplicates",
      "Memory is shared between passes",
    ],
    correctIndex: 0,
    explanation: "LSD radix relies on the previous (less significant) digit's order being preserved by a stable sort on the next digit.",
    difficulty: "hard",
  },
  {
    id: "radix-5", topic: "radix", kind: "true-false",
    prompt: "Radix sort can sort floating-point numbers as easily as integers.",
    correct: false,
    explanation: "Floats need bit manipulation (sign, exponent, mantissa flips for negatives) before radix can handle them. Tricky but possible.",
    difficulty: "hard",
  },
  {
    id: "radix-6", topic: "radix", kind: "fill-blank",
    prompt: "The number of passes radix sort makes equals the maximum number of ____ in any key.",
    accepted: ["digits", "characters"],
    explanation: "k passes for k-digit keys. Each pass uses a stable bucket/counting sort.",
    difficulty: "easy",
  },

  // ── ADDITIONAL: GRAPHS ─────────────────────────────────────────────────────
  {
    id: "graph-6", topic: "graphs", kind: "multiple-choice",
    prompt: "What is the time complexity of DFS on a graph with V vertices and E edges (using adjacency list)?",
    choices: ["O(V)", "O(E)", "O(V + E)", "O(V²)"],
    correctIndex: 2,
    explanation: "Each vertex visited once (O(V)), each edge inspected once (O(E)) — total O(V+E).",
    difficulty: "easy",
  },
  {
    id: "graph-7", topic: "graphs", kind: "true-false",
    prompt: "A directed graph with V vertices can have up to V² edges (including self-loops).",
    correct: true,
    explanation: "Each ordered pair (u,v) is a possible edge. With self-loops allowed: V² edges.",
    difficulty: "easy",
  },
  {
    id: "graph-8", topic: "graphs", kind: "ordering",
    prompt: "Order the steps of topological sort using Kahn's algorithm:",
    items: [
      "Add vertices with in-degree 0 to a queue",
      "Compute in-degree of each vertex",
      "Repeat: remove from queue, output, decrement neighbors' in-degrees",
      "Build the graph",
    ],
    correctOrder: [3, 1, 0, 2],
    explanation: "Build → compute in-degrees → seed queue with sources → repeatedly drain.",
    difficulty: "hard",
  },
  {
    id: "graph-9", topic: "graphs", kind: "multiple-choice",
    prompt: "Which traversal can be used to detect a cycle in a directed graph?",
    choices: [
      "BFS only",
      "DFS with three node colors (white/gray/black)",
      "Dijkstra's algorithm",
      "Kruskal's algorithm",
    ],
    correctIndex: 1,
    explanation: "DFS with coloring: gray = currently exploring, black = finished. Edge to a gray node = back edge = cycle.",
    difficulty: "hard",
  },
  {
    id: "graph-10", topic: "graphs", kind: "multi-select",
    prompt: "Which characterize a tree (in graph terms)?",
    choices: [
      "Connected",
      "Acyclic",
      "n vertices, n-1 edges",
      "Has at least one cycle",
      "Always directed",
    ],
    correctIndices: [0, 1, 2],
    explanation: "Tree = connected + acyclic + n-1 edges. Any two of these imply the third.",
    difficulty: "medium",
  },
  {
    id: "graph-11", topic: "graphs", kind: "fill-blank",
    prompt: "A vertex whose removal disconnects the graph is called an articulation point or ____.",
    accepted: ["cut vertex", "cutvertex"],
    explanation: "Articulation points / cut vertices — found via DFS with low-link values (Tarjan's algorithm).",
    difficulty: "hard",
  },

  // ── ADDITIONAL: SHORTEST PATHS ─────────────────────────────────────────────
  {
    id: "sp-5", topic: "shortest", kind: "multiple-choice",
    prompt: "Bellman-Ford runs in time:",
    choices: ["O(V)", "O(V + E)", "O(V × E)", "O(V³)"],
    correctIndex: 2,
    explanation: "V-1 iterations, each relaxing all E edges — total O(V·E).",
    difficulty: "medium",
  },
  {
    id: "sp-6", topic: "shortest", kind: "true-false",
    prompt: "Bellman-Ford can detect negative-weight cycles reachable from the source.",
    correct: true,
    explanation: "After V-1 relaxations, run one more pass. Any further relaxation indicates a negative cycle.",
    difficulty: "medium",
  },
  {
    id: "sp-7", topic: "shortest", kind: "multiple-choice",
    prompt: "A* differs from Dijkstra by using:",
    choices: [
      "Negative weights",
      "A heuristic estimate of distance to goal",
      "Floyd-Warshall internally",
      "DFS instead of BFS",
    ],
    correctIndex: 1,
    explanation: "A* explores nodes prioritized by g(n) + h(n) where h is a heuristic. With admissible h, it's optimal.",
    difficulty: "medium",
  },
  {
    id: "sp-8", topic: "shortest", kind: "matching",
    prompt: "Match the algorithm to its best use case:",
    pairs: [
      { left: "Dijkstra",        right: "Single-source, non-negative weights" },
      { left: "Bellman-Ford",    right: "Single-source, allows negative weights" },
      { left: "Floyd-Warshall",  right: "All-pairs shortest paths" },
      { left: "BFS",             right: "Unweighted graph" },
    ],
    explanation: "Pick by: source-count, weight signs, and graph density.",
    difficulty: "medium",
  },
  {
    id: "sp-9", topic: "shortest", kind: "fill-blank",
    prompt: "The process of updating dist[v] = min(dist[v], dist[u] + w(u,v)) is called edge ____.",
    accepted: ["relaxation", "relax"],
    explanation: "Edge relaxation is the core operation in shortest-path algorithms — try to improve v's distance via u.",
    difficulty: "medium",
  },

  // ── ADDITIONAL: SPANNING TREES ─────────────────────────────────────────────
  {
    id: "span-5", topic: "span", kind: "multiple-choice",
    prompt: "Prim's algorithm runs in O((V+E) log V) using a:",
    choices: ["Stack", "Sorted edge list", "Min-priority queue", "Hash map"],
    correctIndex: 2,
    explanation: "Prim's grows the tree by repeatedly extracting the cheapest connecting edge — natural fit for a min-PQ.",
    difficulty: "medium",
  },
  {
    id: "span-6", topic: "span", kind: "true-false",
    prompt: "If all edge weights are distinct, the MST is unique.",
    correct: true,
    explanation: "Distinct weights ensure a unique tie-break at every cut, yielding a unique MST.",
    difficulty: "hard",
  },
  {
    id: "span-7", topic: "span", kind: "multiple-choice",
    prompt: "The cut property of MSTs states:",
    choices: [
      "Every cycle in an MST is empty",
      "The lightest edge crossing any cut is in some MST",
      "All MSTs have the same total weight",
      "Removing any edge disconnects the graph",
    ],
    correctIndex: 1,
    explanation: "Cut property: for any cut, the min-weight edge crossing it belongs to some MST. Justifies Prim/Kruskal greediness.",
    difficulty: "hard",
  },
  {
    id: "span-8", topic: "span", kind: "fill-blank",
    prompt: "Kruskal's algorithm processes edges in ascending weight order using a ____-Find data structure.",
    accepted: ["Union", "union"],
    explanation: "Union-Find detects cycles in O(α(n)) — nearly constant time.",
    difficulty: "easy",
  },
];
